### ISSUE TITLE
Can't run wtf-trace cli tool (bad 2014.1.23-1 npm deployment?)

### ISSUE THREAD

**Issue by lpetre** [google/tracing-framework#473]
There is a lot missing in the latest npm release. This appears to be a regression of #419 

I get the following error when running wtf-trace:

```
Unable to find wtf_node_js_compiled.js
```

Here are the npm install logs:

```
$  npm install -g tracing-framework
npm http GET https://registry.npmjs.org/tracing-framework
npm http 304 https://registry.npmjs.org/tracing-framework
npm http GET https://registry.npmjs.org/falafel/0.1.4
npm http GET https://registry.npmjs.org/mkdirp/0.3.5
npm http GET https://registry.npmjs.org/ws/0.4.25
npm http GET https://registry.npmjs.org/optimist/0.3.5
npm http GET https://registry.npmjs.org/string-hash
npm http GET https://registry.npmjs.org/temporary/0.0.7
npm http GET https://registry.npmjs.org/microtime/0.3.3
npm http 304 https://registry.npmjs.org/optimist/0.3.5
npm http 304 https://registry.npmjs.org/string-hash
npm http 304 https://registry.npmjs.org/ws/0.4.25
npm http 304 https://registry.npmjs.org/temporary/0.0.7
npm http 304 https://registry.npmjs.org/mkdirp/0.3.5
npm http 304 https://registry.npmjs.org/falafel/0.1.4
npm http 304 https://registry.npmjs.org/microtime/0.3.3
npm http GET https://registry.npmjs.org/esprima/1.0.0
npm http GET https://registry.npmjs.org/package
npm http GET https://registry.npmjs.org/wordwrap
npm http 304 https://registry.npmjs.org/esprima/1.0.0
npm http GET https://registry.npmjs.org/bindings/1.0.0
npm http 304 https://registry.npmjs.org/wordwrap
npm http 304 https://registry.npmjs.org/bindings/1.0.0
npm http GET https://registry.npmjs.org/commander
npm http GET https://registry.npmjs.org/tinycolor
npm http GET https://registry.npmjs.org/options

> microtime@0.3.3 install /usr/local/lib/node_modules/tracing-framework/node_modules/microtime
> node-gyp rebuild

2014-05-05 19:58:08.121 xcodebuild[10442:1207] [MT] PluginLoading: Required plug-in compatibility UUID A2E4D43F-41F4-4FB9-BB94-7177011C9AED for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Unity4XC.xcplugin' not present in DVTPlugInCompatibilityUUIDs
  CXX(target) Release/obj.target/microtime/src/microtime.o
  SOLINK_MODULE(target) Release/microtime.node
  SOLINK_MODULE(target) Release/microtime.node: Finished
npm http 304 https://registry.npmjs.org/package
npm http 304 https://registry.npmjs.org/tinycolor
npm http 304 https://registry.npmjs.org/commander
npm http 304 https://registry.npmjs.org/options

> ws@0.4.25 install /usr/local/lib/node_modules/tracing-framework/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node
  SOLINK_MODULE(target) Release/bufferutil.node: Finished
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node
  SOLINK_MODULE(target) Release/validation.node: Finished
/usr/local/bin/wtf-controller -> /usr/local/lib/node_modules/tracing-framework/bin/controller.js
/usr/local/bin/wtf-generate-webgl-app -> /usr/local/lib/node_modules/tracing-framework/bin/generate-webgl-app.js
/usr/local/bin/wtf-diff -> /usr/local/lib/node_modules/tracing-framework/bin/diff.js
/usr/local/bin/wtf-dump -> /usr/local/lib/node_modules/tracing-framework/bin/dump.js
/usr/local/bin/wtf-query -> /usr/local/lib/node_modules/tracing-framework/bin/query.js
/usr/local/bin/wtf-instrument -> /usr/local/lib/node_modules/tracing-framework/bin/instrument.js
/usr/local/bin/wtf-save-trace -> /usr/local/lib/node_modules/tracing-framework/bin/save-trace.js
/usr/local/bin/wtf-trace -> /usr/local/lib/node_modules/tracing-framework/bin/trace-runner.js
tracing-framework@2014.1.23-1 /usr/local/lib/node_modules/tracing-framework
├── string-hash@1.1.0
├── mkdirp@0.3.5
├── optimist@0.3.5 (wordwrap@0.0.2)
├── temporary@0.0.7 (package@1.0.1)
├── falafel@0.1.4 (esprima@1.0.0)
├── microtime@0.3.3 (bindings@1.0.0)
└── ws@0.4.25 (tinycolor@0.0.1, options@0.0.5, commander@0.6.1)
```

There is no build-out directory:

```
$ ls -alF node_modules/tracing-framework/build-out
ls: node_modules/tracing-framework/build-out: No such file or directory
```

**Comment by mindplay-dk** [comment]
Not sure if this is a duplicate or not - I also can't run `wtf-trace`, but I get a different error.

```
C:\workspace\node\orient>node app.js
Using database: sample
Person:  Bob
Person:  John
Person:  Charlie
has tools...
- has Tool:  Hammer
select: 69ms
^C
C:\workspace\node\orient>wtf-trace app.js

module.js:338
    throw err;
          ^
Error: Cannot find module 'oriento'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at relativeRequire (C:\Users\Rasmus\AppData\Roaming\npm\node_modules\tracing-framework\bin\trace-runner.js:75:10)
    at C:\workspace\node\orient\app.js:1:15
    at Object.exports.runInContext (vm.js:64:17)
    at Object.<anonymous> (C:\Users\Rasmus\AppData\Roaming\npm\node_modules\tracing-framework\bin\trace-runner.js:94:4)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)

C:\workspace\node\orient>node -v
v0.12.0
C:\workspace\node\orient>ver
Microsoft Windows [Version 6.3.9600]
```

As you can see, my app runs - but when trying to run under `wtf-trace`, the module loader fails for some reason.

wtf? ;-)

**Comment by aa6** [comment]
Same problem as @mindplay-dk has: cannot find module.

**Comment by mathewmeconry** [comment]
some here as @aa6 and @mindplay-dk has: cannot find module.
