### ISSUE TITLE
ReferenceError: require is not defined

### ISSUE THREAD

**Issue by Spy-Seth** [google/tracing-framework#533]
I'm trying to use WTF to trace my application server. I get a surprising error: `ReferenceError: require is not defined`

```
$ wtf-trace server.js
/Users/spy-seth/workspace/web.client.vlr/server.js:3
var newrelic = require('newrelic');
               ^
ReferenceError: require is not defined
    at /Users/spy-seth/workspace/web.client.vlr/server.js:3:16
    at Object.exports.runInThisContext (vm.js:74:17)
    at Object.<anonymous> (/Users/spy-seth/.nvm/versions/node/v0.12.4/lib/node_modules/tracing-framework/bin/trace-runner.js:66:4)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

server.js
```javascript
'use strict';

var newrelic = require('newrelic');
```

**Comment by joaomlneto** [comment]
Same problem. Running on OSX Yosemite (10.10.4).
@Spy-Seth From the path in your trace (/Users) I reckon you may be using the same OS :)
It is probably OS-related.

**Comment by Spy-Seth** [comment]
You right, I'm the same version as you.

**Comment by eknath-iyer** [comment]
Observed in centos as well

**Comment by rsturgell** [comment]
It's not too surprising, wtf-trace does some tricky stuff with require. What version of node?

**Comment by joaomlneto** [comment]
I'm using v0.12.6 (just tried to reproduce it again)
$ npm install -g tracing-framework
$ node myapp.js
ReferenceError: require is not defined

**Comment by rsturgell** [comment]
@Spy-Seth - from that call stack it looks like you're using an old version. trace-runner.js doesn't call runInThisContext, it now calls runInContext. Looks like this changed back in August 2013. Maybe try updating?

@joaomlneto - I'm not able to repro, do you have a small repro case I can try? I noticed you aren't actually using wtf-trace to run your app, maybe a different issue? Do you have a call stack or does it just print what you quoted?

**Comment by Spy-Seth** [comment]
@rsturgell I've try WTF after an `npm install WTF -g`... I think I've one of the last version published. But I could check.

**Comment by rsturgell** [comment]
@Spy-Seth I think that should be `npm install tracing-framework -g`

**Comment by Spy-Seth** [comment]
ha it's was I do. Just a typo error in the comment.

**Comment by joaomlneto** [comment]
@rsturgell Sorry, I mistyped :) I'm indeed running it with wtf-trace.

    $ node -v
    v0.12.6

    $ npm -v
    2.11.2

    $ cat test.js
    Http = require('http');
    console.log('hello world');

    $ wtf-trace test.js
    /Users/joaomlneto/Desktop/test.js:1
    Http = require('http');
           ^
    ReferenceError: require is not defined
        at /Users/joaomlneto/Desktop/test.js:1:8
        at Object.exports.runInThisContext (vm.js:74:17)
        at Object.<anonymous> (/usr/local/lib/node_modules/tracing-framework/bin/trace-runner.js:66:4)
        at Module._compile (module.js:460:26)
        at Object.Module._extensions..js (module.js:478:10)
        at Module.load (module.js:355:32)
        at Function.Module._load (module.js:310:12)
        at Function.Module.runMain (module.js:501:10)
        at startup (node.js:129:16)
        at node.js:814:3

**Comment by rsturgell** [comment]
Yikes, ok, I think I understand this a little better now.

If you `npm install tracing-framework` under node 0.10, it installs the latest version (2015.7.6-1), but if you install under node 0.12 it installs a very old version (0.0.23), which doesn't work (as described above).

I think the problem may be that tracing-framework depends on microtime 0.3.3, which is maybe incompatible with newer versions of node. In 0.0.23 it looks like there aren't any dependencies, so that installs fine.

This is well past my knowledge of npm, though - @benvanik, do you have any ideas? Should we just update the dependency versions?

**Comment by benvanik** [comment]
I haven't played with it in awhile and only have node v10, but I just tried with the latest microtime and things still seem to work. I'll bump the package and push to npm today and hopefully that'll fix things!

**Comment by benvanik** [comment]
This update should hit NPM soon. Let me know if you guys see things working (after an npm install -g).

**Comment by joaomlneto** [comment]
I'm still having the same problem.
I also tried removing it and reinstalling with -g (apparently I had installed it only locally), but same error.
Maybe I messed something up -- hopefully someone else will try it as well.

    $ npm update
    tracing-framework@2015.7.15-1 node_modules/tracing-framework
    ├── string-hash@1.1.0
    ├── mkdirp@0.3.5
    ├── optimist@0.3.5 (wordwrap@0.0.3)
    ├── temporary@0.0.7 (package@1.0.1)
    ├── falafel@0.1.4 (esprima@1.0.0)
    ├── microtime@1.4.2 (bindings@1.2.1)
    └── ws@0.4.25 (tinycolor@0.0.1, options@0.0.6, commander@0.6.1)

    $ node -v
    v0.12.7

    $ npm -v
    2.11.3

    $ wtf-trace test.js
    /Users/joaomlneto/test.js:1
    var Http = require('http');
               ^
    ReferenceError: require is not defined
        at /Users/joaomlneto/test.js:1:12
        at Object.exports.runInThisContext (vm.js:74:17)
        at Object.<anonymous> (/usr/local/lib/node_modules/tracing-framework/bin/trace-runner.js:66:4)
        at Module._compile (module.js:460:26)
        at Object.Module._extensions..js (module.js:478:10)
        at Module.load (module.js:355:32)
        at Function.Module._load (module.js:310:12)
        at Function.Module.runMain (module.js:501:10)
        at startup (node.js:129:16)
        at node.js:814:3

**Comment by benvanik** [comment]
Hmm darn, not sure then. Can you look at /usr/local/lib/node_modules/tracing-framework/ and see what package.json is in there? When you reinstalled did you blow that entire folder away?

**Comment by joaomlneto** [comment]
No, but I did now. :)
I got the same problem, but noticed something strange in the package.json -- namely the dependencies.
I don't know if this is standard npm behavior or not, but it's quite different from the one in the repository.

    $ sudo npm uninstall -g tracing-framework
    unbuild tracing-framework@0.0.23

    $ ls /usr/local/lib/node_modules/tracing-framework
    ls: /usr/local/lib/node_modules/tracing-framework: No such file or directory

    $ sudo npm install -g tracing-framework
    /usr/local/bin/wtf-trace -> /usr/local/lib/node_modules/tracing-framework/bin/trace-runner.js
    /usr/local/bin/wtf-dump -> /usr/local/lib/node_modules/tracing-framework/bin/dump.js
    tracing-framework@0.0.23 /usr/local/lib/node_modules/tracing-framework

    $ ls /usr/local/lib/node_modules/tracing-framework
    AUTHORS         CONTRIBUTORS.md LICENSE         README.md       bin             build-out       docs            package.json

And the package.json in the directory looks like this:

    $ cat /usr/local/lib/node_modules/tracing-framework/package.json
    {
      "name": "tracing-framework",
      "version": "0.0.23",
      "description": "Web Tracing Framework instrumentation and analysis library.",
      "keywords": [
        "javascript",
        "debugging",
        "tracing",
        "performance"
      ],
      "license": "BSD",
      "homepage": "https://github.com/google/tracing-framework",
      "bugs": {
        "url": "https://github.com/google/tracing-framework/issues"
      },
      "repository": {
        "type": "git",
        "url": "git+ssh://git@github.com/google/tracing-framework.git"
      },
      "engines": {
        "node": ">=0.8.14"
      },
      "scripts": {},
      "dependencies": {},
      "devDependencies": {
        "mocha": "1.4.2",
        "chai": "1.2.0"
      },
      "files": [
        "build-out/wtf_node_js_compiled.js",
        "bin/",
        "AUTHORS",
        "CONTRIBUTORS.md",
        "LICENSE",
        "docs/node.md",
        "docs/options.md",
        "docs/wtf-json.md",
        "docs/wtf-trace.md"
      ],
      "main": "./build-out/wtf_node_js_compiled",
      "bin": {
        "wtf-trace": "./bin/trace-runner.js",
        "wtf-dump": "./bin/dump.js"
      },
      "contributors": [
        {
          "name": "Google, Inc."
        }
      ],
      "_id": "tracing-framework@0.0.23",
      "dist": {
        "shasum": "15d2275e8c8c5bfc92821346af976856c49f5785",
        "tarball": "http://localhost:4873/tracing-framework/-/tracing-framework-0.0.23.tgz"
      },
      "_npmVersion": "1.1.66",
      "_npmUser": {
        "name": "benvanik",
        "email": "" // edit: hidden
      },
      "maintainers": [
        {
          "name": "benvanik",
          "email": "" // edit: hidden
        }
      ],
      "directories": {},
      "_shasum": "15d2275e8c8c5bfc92821346af976856c49f5785",
      "_resolved": "http://localhost:4873/tracing-framework/-/tracing-framework-0.0.23.tgz",
      "_from": "tracing-framework@*",
      "readme": "ERROR: No README data found!"
    }

**Comment by thomask** [comment]
Any updates on this?

**Comment by vhf** [comment]
```
$ node -v
v5.3.0
$ npm -v
3.3.12
$ npm install -g tracing-framework
/usr/local/lib
└── tracing-framework@0.0.23
```
I also got an old version.

And when I manually choose the latest version, microtime does not compile:

```
$ npm install -g tracing-framework@2015.7.15-1
 CXX(target) Release/obj.target/microtime/src/microtime.o
In file included from ../src/microtime.cc:11:
../../nan/nan.h:261:25: error: redefinition of '_NanEnsureLocal'
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                        ^
../../nan/nan.h:256:25: note: previous definition is here
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Handle<T> val) {
                        ^
../../nan/nan.h:661:13: error: no member named 'smalloc' in namespace 'node'
    , node::smalloc::FreeCallback callback
      ~~~~~~^
../../nan/nan.h:672:12: error: no matching function for call to 'New'
    return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
           ^~~~~~~~~~~~~~~~~
/Users/victor/.node-gyp/5.3.0/include/node/node_buffer.h:31:40: note: candidate function not viable: no known conversion from 'uint32_t' (aka 'unsigned int') to 'enum encoding' for 3rd argument
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
```
